create database order_info;
use order_info;
create table order_info(order_id int primary key,o_loc varchar(20) ,o_cost int,created_at timestamp,created_by varchar(20),modified_at timestamp,modified_by varchar(20));
insert into order_info values(1,'Rajaji nagar',269,now(),'mahesh',now(),'Alexa');
insert into order_info values(2,'Rajrajeshwari nagar',399,now(),'saiprit',now(),'siri');
insert into order_info values(3,'vijayanagar',169,now(),'swati',now(),'simran');
insert into order_info values(4,'malleshwaram',799,now(),'mallika',now(),'maya');
insert into order_info values(5,'methikeri',499,now(),'rahul',now(),'laxmi');
desc order_info;
select * from order_info;
create table payment_info(id int,price int,payment_id int primary key,payment_status varchar(20), order_id int,created_at timestamp,created_by varchar(20),modified_at timestamp,modified_by varchar(20),foreign key(order_id) references order_info(order_id));
insert into payment_info values(111,201,20124,'online',1,now(),'soumya',now(),'satwik');
insert into payment_info values(112,202,20125,'cash mode',2,now(),'sushil',now(),'raman');
insert into payment_info values(113,203,20126,'pending',3,now(),'sangeeta',now(),'ram');
insert into payment_info values(114,204,20127,'not paid',4,now(),'mamata',now(),'omkar');
insert into payment_info values(115,205,20128,'paid',5,now(),'bhavani',now(),'aishwarya');
desc payment_info;
select * from payment_info;
create table restaurant_info(id int,r_name varchar(20),r_id primary key,r_location varchar(20),order id int,r_ratings int,payment_id foreign key,created_at timestamp,created_by varchar(20),modified_at timestamp,modified_by varchar(20));